### PR TITLE
Add eslint/prettier and fix linter warnings

### LINKED ISSUE #18: Use eslint for linting
See https://github.com/typescript-eslint/typescript-eslint for reference.

### PR DESCRIPTION
**Pull request by rzgry**
Closes #18 

* Add eslint and fixes linter warnings
* Adds prettier
*  Update command description to `MicroProfile: Generate a new MicroProfile starter project`

Signed-off-by: Ryan Zegray <ryan.zegray@gmail.com>

### CODE REVIEW

File: src/util/starter.ts [hunk 1]
```diff
@@ -1,199 +1,100 @@
...
-                } else {
-                    vscode.window.showErrorMessage("Could not generate an MicroProfile starter project.");
-                }
-            }
-
-            await request(options, callback).pipe(fs.createWriteStream(targetDir + '/' + artifactId + '.zip'));
-        } else {
-            vscode.window.showErrorMessage(error);
-        }
+    // ask user to select one of the servers that are avalaible for the version of mp they selected
```
Comment (kathrynkodama) [inline src/util/starter.ts]: misspelled `available`

File: src/util/util.ts [hunk 2]
```diff
@@ -1,75 +1,186 @@
...
+
+  return await vscode.window.showQuickPick(SUPPORTED_JAVA_SE_VERSIONS, {
+    ignoreFocusOut: true,
+    placeHolder: "Select a Java SE version.",
+  });
+}
+
+export async function askForMPVersion(mpVersions: string[]): Promise<string | undefined> {
+  interface MPVersionOption extends QuickPickItem {
+    label: string; // label is the long-name that is displaed in vscode
```
Comment (kathrynkodama) [inline src/util/util.ts]: misspelled `displayed` (also on line 84)

File: src/util/util.ts [hunk 3]
```diff
@@ -1,75 +1,186 @@
...
+  return undefined;
 }
 
-export function getKeyFromValue(value: Object, arr : any) {
-	return Object.keys(arr).find(key => arr[key] === value);
+interface RequestOptions {
+  url: string;
 }
 
+// Downloads a file using streams to avoid loading entire file into memowry
```
Comment (kathrynkodama) [inline src/util/util.ts]: misspelled `memory`

File: src/util/starter.ts [hunk 4]
```diff
@@ -1,199 +1,100 @@
...
+      groupId: groupId,
+      artifactId: artifactId,
+      mpVersion: mpVersion,
+      supportedServer: mpServer,
+      javaSEVersion: javaSEVersion,
+      selectedSpecs: mpSpecifications,
+    };
+
+    // location to download the zip file
+    const zipPath = targetDirString + "/" + artifactId + ".zip";
```
Comment (kathrynkodama) [inline src/util/starter.ts]: perhaps instead of "/" we should use `path.sep` from [path module](https://www.google.com/search?q=require+path+node+js&oq=require+path+node+js&aqs=chrome..69i57j0l7.4071j0j7&sourceid=chrome&ie=UTF-8)

File: src/util/util.ts [hunk 5]
```diff
@@ -1,75 +1,186 @@
...
-				apiSpec = getKeyFromValue(element, descriptions);
-				dataString += ', "' + apiSpec + '"';
-			}
-		});
-		dataString = dataString + ']';
-	}
-	return dataString;
+export function capitalizeFirstLetter(newString: string): string {
+  return newString.charAt(0).toUpperCase() + newString.slice(1);
 }
```
Comment (kathrynkodama) [inline src/util/util.ts]: trim the string with `newString = newString.trim()` to remove leading whitespace

File: src/util/util.ts [hunk 6]
```diff
@@ -1,75 +1,186 @@
...
+    detail: string; // description of mp spec
+  }
+
+  const mpSpecOptions: MPSpecOption[] = specs.map(spec => {
+    const fullDescription = specDescriptions[spec];
+    const [name, desc] = fullDescription.split("-");
+    return {
+      spec: spec,
+      label: name,
+      detail: desc,
```
Comment (kathrynkodama) [inline src/util/util.ts]: can change this to `detail: capitalizeFirstLetter(desc)` now that you have this method implemented.

File: src/util/starter.ts (hunk 4 above)
Comment (rzgry) [reply src/util/starter.ts]: Changed to use `path.join` which joins them using the platform-specific separator.

**Review by kathrynkodama — APPROVED** [review]
